name        ="sita-sig-swa-pacfilehost"
domain      ="sita.aero"
location    ="eastus"
connection_string = "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=sitasigswastorage;AccountKey=xxxxx;Endpoint=sitasigswastorage.blob.core.windows.net"
containername = "website"
