name        ="swa-sig-flex-proxypacfilehost"
domain      ="signgp.aero"
location    ="eastus2"
connection_string = "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=sitasigswastorage;AccountKey=xxxxx;Endpoint=sitasigswastorage.blob.core.windows.net"
containername = "website"
resgroupname = "sita-sig-swa-pacfilehost"
applocation = "/build"
cname_record = "flexpacfilehost"
dnsresourcegroup = "rg-sita-ngp-sig-use-azuredns"