name        ="swa-sig-sita-flx-proxypachost"
domain      ="signgp.aero"
location    ="westus2"
connection_string = "DefaultEndpointsProtocol=https;EndpointSuffix=core.windows.net;AccountName=sitasigswastorage;AccountKey=xxxxx;Endpoint=sitasigswastorage.blob.core.windows.net"
#containername = "website"
resgroupname = "rg-sita-sig-flx-swa-pacfilehost"
applocation = "/build"
cname_record = "flexsigswapacfile"
dnsresourcegroup = "rg-sita-ngp-sig-use-azuredns"
#resgroupid = "/subscriptions/f3e5381e-28a5-4ede-a3c9-6850bac5232f/resourceGroups/sita-sig-swa-pacfilehost"